=== lorgaco/lroP4/tvml14.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="Programacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Fecha" type="DateType"/>
                <xs:element name="Canal" type="CanalType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="DateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}/[0-9]{2}/[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="CanalType">
        <xs:sequence>
            <xs:element name="NombreCanal" type="xs:string"/>
            <xs:element name="Formato" type="FormatType" minOccurs="0"/>
            <xs:element name="Programa" type="ProgramType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="lang" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="es|en|fr|de|it"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="teletexto" default="no">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="si|no"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="FormatType">
        <xs:restriction base="xs:string">
            <xs:pattern value="4:3|16:9"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ProgramType" mixed="true">
        <xs:sequence>
            <xs:element name="NombrePrograma" type="xs:string"/>
            <xs:element name="Categoria" type="CategoryType"/>
            <xs:element name="Intervalo" type="EmissionType"/>
        </xs:sequence>
        <xs:attribute name="edadminima" type="xs:integer" use="required"/>
        <xs:attribute name="langs" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="CategoryType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Informativos|Cine|Deportes|Infantiles|Documentales"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EmissionType">
        <xs:sequence>
            <xs:element name="HoraInicio" type="TimeType"/>
            <xs:choice>
                <xs:element name="Duracion" type="xs:integer"/>
                <xs:element name="HoraFin" type="TimeType"/>
            </xs:choice>
            <xs:element name="OtraEmision" type="LinkType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TimeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-2][0-9]:[0-6][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="LinkType">
        <xs:sequence>
            <xs:element name="Fecha" type="DateType"/>
            <xs:element name="UrlTVML" type="xs:anyURI" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== lorgaco/lroP4/tvml-ok3.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>

<Programacion
        xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://localhost:8024/lro24/tvml14.xsd">

    <Fecha>23/12/2001</Fecha>

    <Canal lang='es'>
        <NombreCanal>Cuatro</NombreCanal>
        <Programa edadminima='12'>
            Hazlo tu mismo 2
            <NombrePrograma>Bricomania</NombrePrograma>
            <Categoria>Documentales</Categoria>
            <Intervalo>
                <HoraInicio>19:00</HoraInicio>
                <HoraFin>20:00</HoraFin>
            </Intervalo>
        </Programa>
    </Canal>

    <Canal lang='en' teletexto='si'>
        <NombreCanal>HBO</NombreCanal>
        <Formato>16:9</Formato>
        <Programa edadminima='3' langs='es'>
            <NombrePrograma>Game of Thrones</NombrePrograma>
            <Categoria>Cine</Categoria>
            <Intervalo>
                <HoraInicio>15:00</HoraInicio>
                <HoraFin>16:00</HoraFin>
            </Intervalo>
        </Programa>
        <Programa edadminima='8' langs='es en de'>
            <NombrePrograma>Vikingos</NombrePrograma>
            <Categoria>Cine</Categoria>
            <Intervalo>
                <HoraInicio>20:00</HoraInicio>
                <Duracion>75</Duracion>
            </Intervalo>
        </Programa>
    </Canal>

    <Canal lang='it' teletexto='si'>
        <NombreCanal>Discovery Max</NombreCanal>
        <Formato>4:3</Formato>
        <Programa edadminima='8' langs='en es it'>
            <NombrePrograma>Joyas Sobre Ruedas</NombrePrograma>
            <Categoria>Documentales</Categoria>
            <Intervalo>
                <HoraInicio>11:00</HoraInicio>
                <HoraFin>13:00</HoraFin>
            </Intervalo>
            Ford Capri
        </Programa>
    </Canal>
</Programacion>

=== lorgaco/lroP4/tvml-ok4.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>

<Programacion
        xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://localhost:8024/lro24/tvml14.xsd">

    <Fecha>17/12/2001</Fecha>

    <Canal lang='en' teletexto='si'>
        <NombreCanal>HBO</NombreCanal>
        <Formato>16:9</Formato>
        <Programa edadminima='3' langs='es'>
            <NombrePrograma>Game of Thrones</NombrePrograma>
            <Categoria>Cine</Categoria>
            <Intervalo>
                <HoraInicio>15:00</HoraInicio>
                <HoraFin>16:00</HoraFin>
            </Intervalo>
        </Programa>
    </Canal>
</Programacion>
